# Generated by Django 2.2.5 on 2019-09-28 10:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('user', 'name')},
        ),
    ]
